#Autoscaler

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contrax-celery
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.celery_replicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contrax-celery
  targetCPUUtilizationPercentage: {{ .Values.celery_target_cpu_usage }}
status: {}

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: contrax-celery-doc-load
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.celery_doc_load_replicas }}
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: contrax-celery-doc-load
  targetCPUUtilizationPercentage: {{ .Values.celery_doc_load_target_cpu_usage }}
status: {}
